/**
 * =====================================================
 * DESIGN PURCHASE REQUEST CONTROLLER
 * =====================================================
 * 
 * PR Creation from BOM with Inventory Check
 * 
 * @author ViralWindow Development Team
 */

const db = require('../config/db');
const crypto = require('crypto');
const uuidv4 = () => crypto.randomUUID();
const {
    DESIGN_STATES,
    DesignStateMachine,
    AuditLogger
} = require('../services/designStateMachine');

// =====================================================
// CREATE PR FROM BOM
// =====================================================
exports.create = async (req, res) => {
    const requestId = uuidv4();
    let connection;

    try {
        const { bomId } = req.params;
        const { pr_type = 'shortage_only', inventory_policy = 'available', reason } = req.body;
        const user = req.user;

        connection = await db.getConnection();
        await connection.beginTransaction();

        // Get BOM with revision
        const [boms] = await connection.query(`
            SELECT b.*, dr.project_id, dr.revision_no, dr.status AS revision_status
            FROM design_bom b
            JOIN design_revisions dr ON b.design_revision_id = dr.id
            WHERE b.id = ?
        `, [bomId]);

        if (boms.length === 0) {
            throw new Error('Không tìm thấy BOM');
        }

        const bom = boms[0];

        // ✅ BACKEND ENFORCE: BOM phải validated hoặc frozen
        if (bom.status !== 'validated' && bom.status !== 'frozen') {
            throw new Error(`BOM phải được validate trước khi tạo PR. Trạng thái hiện tại: ${bom.status}`);
        }

        // Check existing PR in progress
        const [existingPR] = await connection.query(`
            SELECT id, pr_code, status FROM design_purchase_requests 
            WHERE bom_id = ? AND status IN ('draft', 'submitted')
        `, [bomId]);

        if (existingPR.length > 0) {
            throw new Error(`Đã có PR ${existingPR[0].pr_code} đang ở trạng thái ${existingPR[0].status}. Hoàn thành PR này trước khi tạo mới.`);
        }

        // Get BOM lines
        const [bomLines] = await connection.query(
            'SELECT * FROM design_bom_lines WHERE bom_id = ?',
            [bomId]
        );

        if (bomLines.length === 0) {
            throw new Error('BOM không có dòng vật tư nào');
        }

        // Create PR (pr_code auto generated by trigger)
        const [prResult] = await connection.query(`
            INSERT INTO design_purchase_requests 
            (pr_code, project_id, design_revision_id, bom_id, 
             revision_no_snapshot, bom_version_snapshot,
             status, pr_type, inventory_policy, reason, created_by, created_at)
            VALUES ('', ?, ?, ?, ?, ?, 'draft', ?, ?, ?, ?, NOW())
        `, [
            bom.project_id,
            bom.design_revision_id,
            bomId,
            bom.revision_no,
            bom.bom_version,
            pr_type,
            inventory_policy,
            reason,
            user.id
        ]);

        const prId = prResult.insertId;

        // Get generated PR code
        const [prRows] = await connection.query('SELECT pr_code FROM design_purchase_requests WHERE id = ?', [prId]);
        const prCode = prRows[0]?.pr_code || `PR-${prId}`;

        // Update PR code if trigger didn't work
        if (!prRows[0]?.pr_code) {
            const year = new Date().getFullYear();
            const newPrCode = `PR-${year}-${String(prId).padStart(4, '0')}`;
            await connection.query('UPDATE design_purchase_requests SET pr_code = ? WHERE id = ?', [newPrCode, prId]);
        }

        // Create PR lines based on type
        let prLinesCreated = 0;

        for (const bomLine of bomLines) {
            // Calculate qty with waste
            const qtyWithWaste = bomLine.qty * (1 + (bomLine.waste_factor || 0) / 100);

            // Get inventory status
            const inventoryData = await getInventoryStatus(bomLine.material_code_snapshot, connection);

            // Calculate shortage based on policy
            let shortage = 0;
            if (inventory_policy === 'available') {
                shortage = qtyWithWaste - inventoryData.qty_available;
            } else if (inventory_policy === 'on_hand') {
                shortage = qtyWithWaste - inventoryData.qty_on_hand;
            } else if (inventory_policy === 'net_shortage') {
                shortage = qtyWithWaste - (inventoryData.qty_available + inventoryData.qty_on_order);
            }

            // Determine if we should include this line
            let shouldInclude = false;
            if (pr_type === 'full_bom') {
                shouldInclude = true;
            } else if (pr_type === 'shortage_only') {
                shouldInclude = shortage > 0;
            }

            if (shouldInclude) {
                const qtyToOrder = pr_type === 'full_bom' ? qtyWithWaste : Math.max(0, shortage);

                await connection.query(`
                    INSERT INTO design_pr_lines 
                    (pr_id, bom_line_id, material_id, material_code, material_name, uom, qty,
                     qty_on_hand, qty_reserved, qty_available, qty_on_order, qty_shortage,
                     vendor_id, snapshot_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
                `, [
                    prId,
                    bomLine.id,
                    bomLine.material_id,
                    bomLine.material_code_snapshot,
                    bomLine.material_name_snapshot,
                    bomLine.uom_snapshot,
                    parseFloat(qtyToOrder.toFixed(3)),
                    inventoryData.qty_on_hand,
                    inventoryData.qty_reserved,
                    inventoryData.qty_available,
                    inventoryData.qty_on_order,
                    Math.max(0, shortage),
                    bomLine.vendor_id
                ]);

                prLinesCreated++;
            }
        }

        // Update revision status to pr_created
        await connection.query(
            'UPDATE design_revisions SET status = "pr_created", row_version = row_version + 1 WHERE id = ?',
            [bom.design_revision_id]
        );

        // Audit log
        await connection.query(`
            INSERT INTO design_audit_logs 
            (request_id, entity_type, entity_id, action, new_values, user_id, user_name, created_at)
            VALUES (?, 'pr', ?, 'created', ?, ?, ?, NOW())
        `, [
            requestId, prId,
            JSON.stringify({ pr_type, inventory_policy, lines_count: prLinesCreated }),
            user.id, user.full_name
        ]);

        await connection.commit();

        res.json({
            success: true,
            message: `Đã tạo ${prCode} với ${prLinesCreated} dòng`,
            data: {
                pr_id: prId,
                pr_code: prCode,
                lines_count: prLinesCreated,
                pr_type,
                inventory_policy
            }
        });
    } catch (error) {
        if (connection) await connection.rollback();
        console.error('Error creating PR:', error);
        res.status(500).json({ success: false, message: error.message });
    } finally {
        if (connection) connection.release();
    }
};

/**
 * Get inventory status for a material
 */
async function getInventoryStatus(materialCode, connection) {
    // Try to find in inventory tables
    // This is a simplified version - in production, you'd query your actual inventory tables

    try {
        // Try accessories table
        const [accessories] = await connection.query(
            'SELECT quantity as qty_on_hand FROM accessories WHERE code = ?',
            [materialCode]
        );

        if (accessories.length > 0) {
            return {
                qty_on_hand: accessories[0].qty_on_hand || 0,
                qty_reserved: 0,
                qty_available: accessories[0].qty_on_hand || 0,
                qty_on_order: 0
            };
        }

        // Try aluminum_systems table
        const [aluminum] = await connection.query(
            'SELECT total_length as qty_on_hand FROM aluminum_systems WHERE code = ?',
            [materialCode]
        );

        if (aluminum.length > 0) {
            return {
                qty_on_hand: aluminum[0].qty_on_hand || 0,
                qty_reserved: 0,
                qty_available: aluminum[0].qty_on_hand || 0,
                qty_on_order: 0
            };
        }

        // Try inventory table
        const [inventory] = await connection.query(
            'SELECT quantity as qty_on_hand FROM inventory WHERE code = ?',
            [materialCode]
        );

        if (inventory.length > 0) {
            return {
                qty_on_hand: inventory[0].qty_on_hand || 0,
                qty_reserved: 0,
                qty_available: inventory[0].qty_on_hand || 0,
                qty_on_order: 0
            };
        }
    } catch (err) {
        // Table might not exist or other error
        console.log('Inventory check warning:', err.message);
    }

    // Default: material not in inventory
    return {
        qty_on_hand: 0,
        qty_reserved: 0,
        qty_available: 0,
        qty_on_order: 0
    };
}

// =====================================================
// GET PR BY ID
// =====================================================
exports.getById = async (req, res) => {
    try {
        const { prId } = req.params;

        const [prs] = await db.query(`
            SELECT pr.*, 
                   p.project_code, p.project_name,
                   u1.full_name AS created_by_name,
                   u2.full_name AS submitted_by_name,
                   u3.full_name AS approved_by_name
            FROM design_purchase_requests pr
            LEFT JOIN projects p ON pr.project_id = p.id
            LEFT JOIN users u1 ON pr.created_by = u1.id
            LEFT JOIN users u2 ON pr.submitted_by = u2.id
            LEFT JOIN users u3 ON pr.approved_by = u3.id
            WHERE pr.id = ?
        `, [prId]);

        if (prs.length === 0) {
            return res.status(404).json({ success: false, message: 'Không tìm thấy PR' });
        }

        const pr = prs[0];

        // Get PR lines
        const [lines] = await db.query(`
            SELECT pl.*, bl.source_unit_id, du.unit_code AS source_unit_code
            FROM design_pr_lines pl
            LEFT JOIN design_bom_lines bl ON pl.bom_line_id = bl.id
            LEFT JOIN design_units du ON bl.source_unit_id = du.id
            WHERE pl.pr_id = ?
            ORDER BY pl.material_code
        `, [prId]);

        // Group by vendor
        const byVendor = lines.reduce((acc, line) => {
            const vendorId = line.vendor_id || 'no_vendor';
            if (!acc[vendorId]) {
                acc[vendorId] = [];
            }
            acc[vendorId].push(line);
            return acc;
        }, {});

        res.json({
            success: true,
            data: {
                ...pr,
                lines,
                lines_by_vendor: byVendor,
                total_lines: lines.length
            }
        });
    } catch (error) {
        console.error('Error getting PR:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

// =====================================================
// SUBMIT PR (Draft → Submitted)
// =====================================================
exports.submit = async (req, res) => {
    const requestId = uuidv4();
    let connection;

    try {
        const { prId } = req.params;
        const user = req.user;

        connection = await db.getConnection();
        await connection.beginTransaction();

        // Get PR
        const [prs] = await connection.query('SELECT * FROM design_purchase_requests WHERE id = ?', [prId]);

        if (prs.length === 0) {
            throw new Error('Không tìm thấy PR');
        }

        const pr = prs[0];

        if (pr.status !== 'draft') {
            throw new Error(`Chỉ có thể submit PR ở trạng thái Draft. Trạng thái hiện tại: ${pr.status}`);
        }

        // Update PR
        await connection.query(`
            UPDATE design_purchase_requests 
            SET status = 'submitted', submitted_by = ?, submitted_at = NOW(), row_version = row_version + 1
            WHERE id = ?
        `, [user.id, prId]);

        // Audit log
        await connection.query(`
            INSERT INTO design_audit_logs 
            (request_id, entity_type, entity_id, action, user_id, user_name, created_at)
            VALUES (?, 'pr', ?, 'submitted', ?, ?, NOW())
        `, [requestId, prId, user.id, user.full_name]);

        await connection.commit();

        res.json({
            success: true,
            message: `Đã gửi ${pr.pr_code} để duyệt`
        });
    } catch (error) {
        if (connection) await connection.rollback();
        console.error('Error submitting PR:', error);
        res.status(500).json({ success: false, message: error.message });
    } finally {
        if (connection) connection.release();
    }
};

// =====================================================
// APPROVE PR (Submitted → Approved)
// =====================================================
exports.approve = async (req, res) => {
    const requestId = uuidv4();
    let connection;

    try {
        const { prId } = req.params;
        const user = req.user;

        connection = await db.getConnection();
        await connection.beginTransaction();

        // Get PR
        const [prs] = await connection.query('SELECT * FROM design_purchase_requests WHERE id = ?', [prId]);

        if (prs.length === 0) {
            throw new Error('Không tìm thấy PR');
        }

        const pr = prs[0];

        if (pr.status !== 'submitted') {
            throw new Error(`Chỉ có thể duyệt PR đã submitted. Trạng thái hiện tại: ${pr.status}`);
        }

        // Update PR
        await connection.query(`
            UPDATE design_purchase_requests 
            SET status = 'approved', approved_by = ?, approved_at = NOW(), row_version = row_version + 1
            WHERE id = ?
        `, [user.id, prId]);

        // Create inventory reservations
        const [prLines] = await connection.query('SELECT * FROM design_pr_lines WHERE pr_id = ?', [prId]);

        for (const line of prLines) {
            await connection.query(`
                INSERT INTO design_inventory_reservations 
                (project_id, design_revision_id, bom_id, material_id, qty_reserved, reserved_by, reserved_at)
                VALUES (?, ?, ?, ?, ?, ?, NOW())
            `, [
                pr.project_id,
                pr.design_revision_id,
                pr.bom_id,
                line.material_id,
                line.qty,
                user.id
            ]);
        }

        // Audit log
        await connection.query(`
            INSERT INTO design_audit_logs 
            (request_id, entity_type, entity_id, action, new_values, user_id, user_name, created_at)
            VALUES (?, 'pr', ?, 'approved', ?, ?, ?, NOW())
        `, [
            requestId, prId,
            JSON.stringify({ reservations_created: prLines.length }),
            user.id, user.full_name
        ]);

        await connection.commit();

        res.json({
            success: true,
            message: `Đã duyệt ${pr.pr_code}. Đã tạo ${prLines.length} reservation.`
        });
    } catch (error) {
        if (connection) await connection.rollback();
        console.error('Error approving PR:', error);
        res.status(500).json({ success: false, message: error.message });
    } finally {
        if (connection) connection.release();
    }
};

// =====================================================
// REJECT PR
// =====================================================
exports.reject = async (req, res) => {
    const requestId = uuidv4();
    let connection;

    try {
        const { prId } = req.params;
        const { reason } = req.body;
        const user = req.user;

        if (!reason) {
            return res.status(400).json({ success: false, message: 'Vui lòng nhập lý do từ chối' });
        }

        connection = await db.getConnection();
        await connection.beginTransaction();

        // Get PR
        const [prs] = await connection.query('SELECT * FROM design_purchase_requests WHERE id = ?', [prId]);

        if (prs.length === 0) {
            throw new Error('Không tìm thấy PR');
        }

        const pr = prs[0];

        if (pr.status !== 'submitted') {
            throw new Error(`Chỉ có thể từ chối PR đã submitted. Trạng thái hiện tại: ${pr.status}`);
        }

        // Update PR
        await connection.query(`
            UPDATE design_purchase_requests 
            SET status = 'draft', rejected_by = ?, rejected_at = NOW(), rejection_reason = ?, row_version = row_version + 1
            WHERE id = ?
        `, [user.id, reason, prId]);

        // Audit log
        await connection.query(`
            INSERT INTO design_audit_logs 
            (request_id, entity_type, entity_id, action, reason, user_id, user_name, created_at)
            VALUES (?, 'pr', ?, 'rejected', ?, ?, ?, NOW())
        `, [requestId, prId, reason, user.id, user.full_name]);

        await connection.commit();

        res.json({
            success: true,
            message: `Đã từ chối ${pr.pr_code}. PR chuyển về Draft để chỉnh sửa.`
        });
    } catch (error) {
        if (connection) await connection.rollback();
        console.error('Error rejecting PR:', error);
        res.status(500).json({ success: false, message: error.message });
    } finally {
        if (connection) connection.release();
    }
};

// =====================================================
// REFRESH INVENTORY (for PR lines)
// =====================================================
exports.refreshInventory = async (req, res) => {
    let connection;

    try {
        const { prId } = req.params;

        connection = await db.getConnection();

        // Get PR lines
        const [lines] = await connection.query(
            'SELECT * FROM design_pr_lines WHERE pr_id = ?',
            [prId]
        );

        for (const line of lines) {
            const inventoryData = await getInventoryStatus(line.material_code, connection);

            await connection.query(`
                UPDATE design_pr_lines 
                SET qty_on_hand = ?, qty_reserved = ?, qty_available = ?, qty_on_order = ?,
                    qty_shortage = GREATEST(0, qty - ?),
                    snapshot_at = NOW()
                WHERE id = ?
            `, [
                inventoryData.qty_on_hand,
                inventoryData.qty_reserved,
                inventoryData.qty_available,
                inventoryData.qty_on_order,
                inventoryData.qty_available,
                line.id
            ]);
        }

        res.json({
            success: true,
            message: `Đã refresh tồn kho cho ${lines.length} dòng`
        });
    } catch (error) {
        console.error('Error refreshing inventory:', error);
        res.status(500).json({ success: false, message: error.message });
    } finally {
        if (connection) connection.release();
    }
};
